language: node_js
node_js:
  - "10"
cache: npm

notifications:
  email:
    recipients:
      - gentleman_0109@outlook.com # 设置通知邮件
    on_success: change
    on_failure: always

install:
  - npm install -g gitbook-cli
  - gitbook install

script:
  - cd docs # into /docs folder
  - gitbook build

after_script:
  - cd _book
  - git init
  - git remote add origin https://${GH_REF}
  # - git config user.name "yubuntu0109"
  # - git config user.email "Gentleman_0109@outlook.com"
  - git add .
  - git commit -m ":rocket:Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force --quiet "https://${GOOGTECH_TOKEN}@${GH_REF}" master:gh-pages

branches:
  only:
    - master

env:
  global:
    - GH_REF: github.com/YUbuntu0109/leetcode-googtech.git # 设置 github 地址


#---------------------------------------------------------------------------------------------------------
# 参考博文如下所示 : 
# <Travis CI持续集成 GitHub 个人博客> : https://www.jianshu.com/p/9d056d5ba78e
# <使用 travis + gitbook + github pages 优雅地发布自己的书> : https://segmentfault.com/a/1190000018002602
#
#
# 注意 GOOGTECH_TOKEN 的命令规范，如果含有特殊字符需要加入转字符哟( 符号 "_" 不是特殊字符 )
# 否则 Travis 控制台会抛出如下异常信息( 符号 "-" 属于特殊字符哟 ) : 
# $ git push --force --quiet "https://${LEETCODE-GOOGTECH-TOKEN}@${GH_REF}" master:gh-pages
# remote: Invalid username or password.
# fatal: Authentication failed for 'https://GOOGTECH-TOKEN@github.com/YUbuntu0109/leetcode-googtech.git/'
#---------------------------------------------------------------------------------------------------------
